Remove bitvec dependency
We use bitvec in encoding (AFAIK only in Zarith encoding implementation). This crate is painful to use, as their
policies on version updates and older version support renders our libraries useless, because they cannot be imported
to any other code, and also renders `cargo install` non-functional.
Trying to import any tezedge library or calling `cargo install` will result in error:
```
error: failed to select a version for the requirement `bitvec = "^0.9.0"`
candidate versions found which didn't match: 0.17.4
```